version: "3"
services:
  eureka-server1:
    hostname: eureka-server1
    image: geekcarnegie/eureka-server-cluster:1.0.0
    restart: always
    networks:
      - springcloud_net
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=eureka-server1
  eureka-server2:
    hostname: eureka-server2
    image: geekcarnegie/eureka-server-cluster:1.0.0
    restart: always
    networks:
      - springcloud_net
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=eureka-server2
networks:
 springcloud_net:
  external:
   name: springcloud