version: "3"
services:
  rabbitmq1:
    hostname: rabbitmq1
    container_name: rabbitmq1
    image: rabbitmq:3.8-management
    restart: always
    networks:
      - rabbitmq_net
    ports:
      - "4370:4369"
      - "5668:5671"
      - "5673:5672"
      - "15673:15672"
      - "25673:25672"
    volumes:
      - "/Users/carnegielee/Desktop/volumes/rabbitmq/data/rabbitmq1:/var/lib/rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: AimcUCUVvHjswSBmTswKh0g4kNj4K7
  rabbitmq2:
    hostname: rabbitmq2
    container_name: rabbitmq2
    image: rabbitmq:3.8-management
    restart: always
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq1
    links:
      - rabbitmq1
    ports:
      - "4371:4369"
      - "5669:5671"
      - "5674:5672"
      - "15674:15672"
      - "25674:25672"
    volumes:
      - "/Users/carnegielee/Desktop/volumes/rabbitmq/data/rabbitmq2:/var/lib/rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: AimcUCUVvHjswSBmTswKh0g4kNj4K7
  rabbitmq3:
    hostname: rabbitmq3
    container_name: rabbitmq3
    image: rabbitmq:3.8-management
    restart: always
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq1
    links:
      - rabbitmq1
    ports:
      - "4372:4369"
      - "5670:5671"
      - "5675:5672"
      - "15675:15672"
      - "25675:25672"
    volumes:
      - "/Users/carnegielee/Desktop/volumes/rabbitmq/data/rabbitmq3:/var/lib/rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: AimcUCUVvHjswSBmTswKh0g4kNj4K7
  haproxy:
    hostname: rabbitmq_haproxy
    container_name: rabbitmq_haproxy
    image: haproxy:latest
    restart: always
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    links:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - "5672:5672"
      - "1080:1080"
    volumes:
      - "/Users/carnegielee/Desktop/volumes/haproxy/rabbitmq/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    environment:
      - CONTAINER_NAME=rabbitmq_haproxy
networks:
 rabbitmq_net:
  external:
   name: rabbitmq
