version: "3"
services:
  redis1:
    hostname: redis1
    container_name: redis1
    image: redis:latest
    restart: always
    networks:
      - redis_net
    ports:
      - "6379:6379"
    links:
      - redis2
      - redis3
    volumes:
      - "/Users/carnegielee/Desktop/volumes/redis/redis1/conf:/usr/local/etc/redis"
      - "/Users/carnegielee/Desktop/volumes/redis/redis1/data:/data"
    command:
      redis-server /usr/local/etc/redis/redis.conf
  redis2:
    hostname: redis2
    container_name: redis2
    image: redis:latest
    restart: always
    networks:
      - redis_net
    ports:
      - "6380:6379"
    volumes:
      - "/Users/carnegielee/Desktop/volumes/redis/redis2/conf:/usr/local/etc/redis"
      - "/Users/carnegielee/Desktop/volumes/redis/redis2/data:/data"
    command:
      redis-server /usr/local/etc/redis/redis.conf
  redis3:
    hostname: redis3
    container_name: redis3
    image: redis:latest
    restart: always
    networks:
      - redis_net
    ports:
      - "6381:6379"
    volumes:
      - "/Users/carnegielee/Desktop/volumes/redis/redis3/conf:/usr/local/etc/redis"
      - "/Users/carnegielee/Desktop/volumes/redis/redis3/data:/data"
    command:
      redis-server /usr/local/etc/redis/redis.conf
  sentinel1:
    hostname: sentinel1
    container_name: sentinel1
    image: redis:latest
    restart: always
    networks:
      - redis_net
    ports:
      - "26379:26379"
    links:
      - redis1
      - redis2
      - redis3
    volumes:
      - "/Users/carnegielee/Desktop/volumes/redis/sentinel1/conf:/usr/local/etc/redis"
      - "/Users/carnegielee/Desktop/volumes/redis/sentinel1/data:/data"
    command:
      redis-sentinel /usr/local/etc/redis/sentinel.conf
  sentinel2:
    hostname: sentinel2
    container_name: sentinel2
    image: redis:latest
    restart: always
    networks:
      - redis_net
    ports:
      - "26380:26379"
    links:
      - redis1
      - redis2
      - redis3
    volumes:
      - "/Users/carnegielee/Desktop/volumes/redis/sentinel2/conf:/usr/local/etc/redis"
      - "/Users/carnegielee/Desktop/volumes/redis/sentinel2/data:/data"
    command:
      redis-sentinel /usr/local/etc/redis/sentinel.conf
  sentinel3:
    hostname: sentinel3
    container_name: sentinel3
    image: redis:latest
    restart: always
    networks:
      - redis_net
    ports:
      - "26381:26379"
    links:
      - redis1
      - redis2
      - redis3
    volumes:
      - "/Users/carnegielee/Desktop/volumes/redis/sentinel3/conf:/usr/local/etc/redis"
      - "/Users/carnegielee/Desktop/volumes/redis/sentinel3/data:/data"
    command:
      redis-sentinel /usr/local/etc/redis/sentinel.conf
networks:
 redis_net:
  external:
   name: redis
