version: "3"
services:
  config-server:
    hostname: config-server
    image: geekcarnegie/config-server-single:1.0.0
    restart: always
    networks:
      - springcloud_net
    ports:
      - "8769:8769"
    volumes:
      - /Users/carnegielee/Desktop/volumes/config-server:/root/config-server
networks:
 springcloud_net:
  external:
   name: springcloud